uhg:
  mysql:
    datasource:
      reports:
        url: jdbc:mysql://dbsrd3986:3306/redis
        driver-class-name: com.mysql.jdbc.Driver
        username: akunam
        password: Ramuanji9
reports:
  batch:
      cron: 0 0 9 ? * FRI

spring:
  jpa:
    properties:
       hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
